name: Deploy main branch to gitub pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Install pipenv
        run: pip install pipenv
      - name: Test
        run: ls -lah && pwd
      - name: Setup pipenv build environment
        run: pipenv install
      - name: Build install
        run: pipenv run make install
      - name: Package install
        run: "cd install && tar cfvz ../../github-pages.tar.gz ./*"
